<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EReader_API</RootNamespace>
    <AssemblyName>EReader_API</AssemblyName>
    <UserSecretsId>daae9875-c710-4547-b444-0c55424ac9f1</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EReader_API.Application\EReader_API.Application.csproj" />
    <ProjectReference Include="..\EReader_API.Infra\EReader_API.Infra.csproj" />
  </ItemGroup>

</Project>
